#!/usr/bin/env python3
import os
import sys
sys.path.append("/usr/bin/downtime/")
import dbget
def adduser(userid):
    print("Creating new user...")
    if dbget.writeval(userid, "authusers") == 0:
        print("User Added.")
    else:
        print("Failed! Have you setup Downtime?")
def banuser(userid):
    print("Downtime must be reconfigured to remove the user.")
def run():
    os.system("systemctl start downtime")
    exit()

#single argument commands
try:
    arg1 = sys.argv[1]
except:
    print("[ERROR] Downtime-CLI: Required 2 Arguments, recieved 0.")
    exit()
if arg1 == "-r" or arg1 == "--run":
    run()

#double arguments commands
try:
    arg1 = sys.argv[1]
    arg2 = sys.argv[2]
except:
    print("[ERROR] Downtime-CLI: Required 2 Arguments, only recieved 1.")
    exit()
if arg1 == "-n" or arg1 == "--new-user":
    adduser(arg2)
if arg1 == "-b" or arg1 == "--ban-user":
    banuser(arg2)
else:
    print("[ERROR] Downtime-CLI: Argument not Recognized.")
