#!/usr/bin/env python3
import os
import sys
import time
import subprocess
sys.path.append("/usr/bin/downtime/")
import dbget
def register():
    print("Ready to Register.")
    os.system("touch /tmp/registration.downtime.lock")
    tcyc = 0
    while tcyc != 30:
        if os.path.exists("/tmp/registration.downtime.lock") == False:
            print("Registration Complete.")
            print("Restarting Downtime...")
            os.system("systemctl restart downtime")
            exit()
        time.sleep(1)
        tcyc = tcyc + 1
    print("Registration Timeout.")
    os.system("rm -rf /tmp/registration.downtime.lock")
def watch(service):
    dbget.writeval(service, "services")
#check if downtime service is running
if subprocess.getoutput("systemctl is-active downtime") != "active":
    print("Starting Downtime...")
    os.system("systemctl start downtime")
    time.sleep(5)
    if subprocess.getoutput("systemctl is-active downtime") != "active":
        print("Downtime Failed to Start!")
        exit()
elif sys.argv[1] == "register":
    register()
elif sys.argv[1] == "watch" and sys.argv[2]:
    watch(sys.argv[2])
else:
    print("Arguments not recognised.")
